---
title: "US_Map_Viz"
author: "Pankaj Shah"
date: "6/29/2019"
output: html_document
---



Lets finish this shark attack analysis and viz using highchart and see if we could do sthg more than this.



Lets be more productive in the morning.




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(maps)
library(ggmap)
```

Using the maps package

```{r}
par(mfrow = c(2, 1))
map("usa")
```

```{r}
map("county")
```

```{r}
map("world", "China")
map.cities(country = "China", capitals = 2)
```


```{r}
# It has label 
map("state", "kentucky")
data(us.cities)
map.cities(us.cities, country = "KY")

# This chart doesnt have a label.
map("state", "New York")
data(us.cities)
map.cities(us.cities, country = "NY")
```


```{r}
data(unemp)
data(county.fips)

# Plot unemployment by country
colors = c("#F1EEF6", "#D4B9DA", "#C994C7", "#DF65B0", "#DD1C77","#980043")
head(unemp)
```

```{r}
head(county.fips)
```

```{r}
unemp$colorBuckets <- as.numeric(cut(unemp$unemp, c(0, 2, 4, 6, 8, 10, 100)))
colorsmatched <- unemp$colorBuckets[match(county.fips$fips, unemp$fips)]

map("county", col = colors[colorsmatched], fill = TRUE, resolution = 0, lty = 0, projection = "polyconic")
```


```{r}
library(maps)
library(ggmap)

# maps, ggplot2, and ggmap are pre-loaded
# Use map_data() to create usa and inspect
usa <- map_data("usa")
usa %>% head(2)
```


```{r}
# Build the map
ggplot(usa, aes(x = long, y = lat, group = group)) +
  geom_polygon() +
  coord_map() +
  theme_nothing()
```


```{r}
# usa, cities, and all libraryd packages are available
library(readr)
cities <- read_tsv('https://assets.datacamp.com/production/course_862/datasets/US_Cities.txt')
head(cities, 2)
```


```{r}
## Need this to get the theme_map() and scale_color_viridis() functions
library(ggthemes)
library(viridis)

# Finish plot 1
ggplot(usa, aes(x = long, y = lat, group = group)) +
  geom_polygon() +
  geom_point(data = cities, aes(group = State, size = Pop_est),col = "red", shape = 16, alpha = 0.6) +
  coord_map() +
  theme_map()
```

```{r}
# Arrange cities
library(dplyr)
cities_arr <- arrange(cities, Pop_est)

# Copy-paste plot 1 and adapt
ggplot(usa, aes(x = long, y = lat, group = group)) +
  geom_polygon(fill = "grey90") +
  geom_point(data = cities_arr, aes(group = State, col = Pop_est),shape = 16, size = 2) +
  coord_map() +
  theme_map() +
  scale_color_viridis()
```

```{r}
# pop and all libraryd packages are available

# Use map_data() to create state
state <- map_data("state")
head(state)
```

```{r}
# Map of states
ggplot(state, aes(x = long, y = lat, fill = region, group = group)) +
  geom_polygon(col = "white") +
  coord_map() +
  theme_nothing()
```


```{r}
# Map of states with populations
ggplot(state, aes(x = long, y = lat, fill = order, group = group)) +
  geom_polygon(col = "white") +
  coord_map() +
  theme_map()
```



```{r}
usa <- map_data("usa")
ggplot() + 
  geom_polygon(data = usa, aes(x=long, y = lat, group = group), fill = "grey", color = "green") + 
  coord_fixed(1.3)
```

```{r}
states <- map_data("state")
florida <- subset(states, region %in% c("florida"))
ggplot(data = florida) + 
    geom_polygon(aes(x = long, y = lat), fill = "orange", color = "yellow")
```









